# Site Settings
title: Start Jekyll
email: oparcollet@flatironinstitute.org
description: >
  TEST
baseurl: "/startjekyll"
url: "http://parcollet.github.io"
github_username:  parcollet
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM
